"""Canonical rate slots, and the parsers that turn a provider's rate name into one.

A rate name is the only place a provider tells us *what* a number prices, and AWS
publishes Bedrock token prices under **three naming generations that are live at the
same time** (measured against the real APIs on 2026-08-31, account-agnostic):

1. `USW2_InputTokenCount_Global`, `USW2_CacheWrite1hInputTokenCount_LCtx_Global_Batch`
   — the CamelCase form used by `bedrock:ListFoundationModelAgreementOffers` for
   Claude Sonnet 4.5 / 4.6 / Haiku 4.5 and everything older.
2. `USW2_input_tokens_global_standard`, `USW2_cache_write_tokens_1h_standard`
   — the snake_case form the same API uses for Claude Opus 4.7 / 4.8 / 5, Sonnet 5
   and Fable 5.
3. `input_tokens_standard`, `cache_write_tokens_30m_long_ctx_flex`
   — the same snake_case shape *without* a region prefix, used for the OpenAI GPT-5.x
   family (one card priced identically in every region).

and the Price List API adds a fourth, dash-separated one:
`USE1-xai.grok-4.6-mantle-input-tokens-global-standard`.

Rather than teach each feed its own string handling, every feed parses into the
`RateDimension` defined here. That is what makes a future rename survivable: a name this
module cannot parse yields `None`, the affected rate is simply not published by the
feed, and the layer underneath (the last-known-good snapshot, then the bundled
floor) keeps charging. **No parser in this module raises on unknown input** — a
provider that renames a dimension must never take the charging path down with it.

The flip side of that leniency is that a dropped name must not silently become a
cheaper price. `select()` therefore refuses to answer unless every token class it
was asked for is present, and the composite source treats a missing slot as "no
opinion" (keep the previous rate) rather than as zero.
"""
from __future__ import annotations

import json
import os
import re
from dataclasses import dataclass
from decimal import Decimal
from typing import Iterable, Mapping, Optional

TOKEN_CLASSES = ("input", "output", "cache_read", "cache_write")

# `geo` is AWS's word for the in-region / cross-region-within-a-geography price
# (what the Price List calls `Regional CRIS` and what an unqualified dimension
# means); `global` is the cheaper world-wide routing price. The distinction is not
# cosmetic: for Claude Opus 5 the two differ by 10% ($5.50 vs $5.00 per MTok
# input), and a gateway that charges the global rate for traffic it sends through a
# `us.` profile under-charges every request.
SCOPES = ("geo", "global")
# Only `standard` is ever charged by this gateway: `batch`, `flex` and `priority`
# are different products that a caller has to ask Bedrock for explicitly, and this
# gateway does not. They are parsed anyway so that a name carrying one of them is
# recognised and *excluded*, rather than falling into the unparsed bucket where a
# future grammar change would be indistinguishable from a tier we simply ignore.
MODES = ("standard", "batch", "flex", "priority")

_PREFIX_DOC = os.path.join(os.path.dirname(os.path.abspath(__file__)),
                           "defaults", "billing_region_prefixes.json")


def _read_prefix_document() -> dict:
    with open(_PREFIX_DOC, encoding="utf-8") as fh:
        return json.load(fh)


def _load_id_suffix_segments() -> list[str]:
    segments = _read_prefix_document().get("id_suffix_segments") or []
    if not isinstance(segments, list) or not all(
        isinstance(s, str) and s for s in segments
    ):
        raise ValueError(f"{_PREFIX_DOC}: 'id_suffix_segments' must be a list of strings")
    return segments


def _load_prefixes() -> dict[str, str]:
    with open(_PREFIX_DOC, encoding="utf-8") as fh:
        doc = json.load(fh)
    prefixes = doc["prefixes"]
    if not isinstance(prefixes, dict) or not prefixes:
        raise ValueError(f"{_PREFIX_DOC}: 'prefixes' must be a non-empty object")
    for prefix, region in prefixes.items():
        if not re.fullmatch(r"[A-Z0-9]+", prefix) or not isinstance(region, str) or not region:
            raise ValueError(f"{_PREFIX_DOC}: bad entry {prefix!r} -> {region!r}")
    return prefixes


# prefix -> region code, and its inverse. Derived from AWS's own Price List data
# (every Bedrock product carries both `regionCode` and a `usagetype` that starts
# with the billing prefix), not from a guess at the naming convention, and
# regenerated by `tests/test_pricing_feeds_prefixes.py` when credentials allow.
BILLING_PREFIXES: dict[str, str] = _load_prefixes()
REGION_TO_PREFIX: dict[str, str] = {region: prefix for prefix, region in BILLING_PREFIXES.items()}


class _Excluded:
    """A name that IS a price, is recognised, and is not one this gateway charges.

    Distinct from `None`, which means "a shape this build does not understand". The
    difference is the whole value of the `unparsed` counter: every Claude rate card
    carries a 1-hour cache-write rate and every model carries provisioned-throughput
    rows, so folding those into `unparsed` would leave it permanently nonzero and make
    "unparsed went up" — the only signal that a token price changed shape — useless.
    """

    __slots__ = ()

    def __repr__(self) -> str:  # pragma: no cover — debugging aid.
        return "EXCLUDED"

    # Deliberately NOT falsy. Making it falsy would let `if not parsed:` collapse it back
    # into `None`, which is the one distinction this type exists to keep, so callers are
    # made to write `is EXCLUDED` / `is None`.


EXCLUDED = _Excluded()


@dataclass(frozen=True)
class RateDimension:
    """What one published number prices.

    `long_ctx` is carried rather than dropped because a long-context rate is a
    *different, higher* price for the same token class; folding it into the base
    slot would let a long-context number win a `max()` and over-charge ordinary
    traffic by a factor that has nothing to do with the request.
    """

    token_class: str
    scope: str
    long_ctx: bool = False
    mode: str = "standard"


# --- CamelCase (generation 1) ------------------------------------------------
_CAMEL_CLASSES = {
    "InputTokenCount": "input",
    "OutputTokenCount": "output",
    "CacheReadInputTokenCount": "cache_read",
    "CacheWriteInputTokenCount": "cache_write",
}
# A TTL-qualified cache write is a different product from the base one — except for
# the DEFAULT TTL, which is the base one under another name. Bedrock's default prompt
# cache lives 5 minutes, and the bundled floor holds that price (Opus 5's $6.875 is
# 1.25x its input rate, the 5-minute rate), so a card that spells the default out as
# `CacheWrite5mInputTokenCount` must map to the base slot rather than be dropped:
# dropping it would leave the cache-write leg permanently on the floor while the
# provider was publishing it all along. Longer TTLs stay excluded — 1h costs double,
# and the rate table has one cache-write leg.
DEFAULT_CACHE_TTL = "5m"
_CAMEL_TTL_CLASSES = re.compile(r"^CacheWrite(\d+[mh])InputTokenCount$")

# --- snake_case (generations 2 and 3) ---------------------------------------
_SNAKE_CLASS_PREFIXES = (
    ("input_tokens", "input"),
    ("output_tokens", "output"),
    ("cache_read_tokens", "cache_read"),
    # The OpenAI cards spell a cache read this way.
    ("cached_input_tokens", "cache_read"),
    ("cache_write_tokens", "cache_write"),
    ("cache_writes_tokens", "cache_write"),
)
_SNAKE_TTL = re.compile(r"^\d+[mh]$")


def _strip_region(name: str) -> tuple[Optional[str], str]:
    """Split a leading billing prefix off a dimension name.

    Returns `(region_code_or_None, rest)`. An unknown leading token is left in
    place: a card that starts with something else is either region-free (the OpenAI
    shape) or a grammar this module does not know, and both are decided further
    down rather than here.
    """
    head, sep, rest = name.partition("_")
    if sep and head in BILLING_PREFIXES:
        return BILLING_PREFIXES[head], rest
    return None, name


# Products that share the rate-card namespace but are not priced per token:
# reserved throughput and provisioned throughput (per TPM-hour / per model-unit-hour),
# model customisation, and stored custom models. They are matched explicitly so that
# skipping them is a decision rather than a parse failure — `unparsed` is the signal
# that a *token* price changed shape, and 1,700 provisioned-throughput names drowning
# it out would make that signal useless.
_NOT_PER_TOKEN = (
    "reserved", "tpm", "provisionedthroughput", "provisioned_throughput",
    "modelunits", "model_units", "customization", "customisation", "storage",
)


def _is_not_per_token(rest: str) -> bool:
    lowered = rest.lower()
    return any(marker in lowered for marker in _NOT_PER_TOKEN)


def parse_agreement_dimension(
    name: str,
) -> Optional[tuple[Optional[str], RateDimension]] | _Excluded:
    """Parse one `ListFoundationModelAgreementOffers` rate-card dimension.

    Three answers, and the difference between the last two matters:

    - `(region_or_None, RateDimension)` — a per-token price this gateway can charge.
    - `EXCLUDED` — recognised, and not a price this gateway charges: reserved or
      provisioned throughput (priced per TPM-hour or model-unit-hour), model
      customisation, stored custom models, a cache write with a non-default TTL.
    - `None` — a shape this build does not understand, which is the signal that a
      provider renamed something.
    """
    if not isinstance(name, str) or not name:
        return None
    region, rest = _strip_region(name)
    if not rest:
        return None
    if _is_not_per_token(rest):
        return EXCLUDED
    parts = rest.split("_")
    ttl = _CAMEL_TTL_CLASSES.match(parts[0])
    if ttl:
        if ttl.group(1) != DEFAULT_CACHE_TTL:
            return EXCLUDED  # a longer TTL is a different product; not charged.
        return _finish_camel(region, "cache_write", parts[1:])
    if parts[0] in _CAMEL_CLASSES:
        return _finish_camel(region, _CAMEL_CLASSES[parts[0]], parts[1:])
    return _finish_snake(region, parts)


def _finish_camel(region: Optional[str], token_class: str,
                  flags: list[str]) -> Optional[tuple[Optional[str], RateDimension]]:
    scope = "geo"
    long_ctx = False
    mode = "standard"
    for flag in flags:
        if flag == "Global":
            scope = "global"
        elif flag == "Geo":
            scope = "geo"
        elif flag == "LCtx":
            long_ctx = True
        elif flag == "Batch":
            mode = "batch"
        else:
            # An unknown qualifier could mean anything, including "this is not the
            # price you think it is". Refuse the whole name.
            return None
    return region, RateDimension(token_class, scope, long_ctx, mode)


def _finish_snake(
    region: Optional[str], parts: list[str],
) -> Optional[tuple[Optional[str], RateDimension]] | _Excluded:
    rest = "_".join(parts)
    token_class = None
    for prefix, klass in _SNAKE_CLASS_PREFIXES:
        if rest == prefix or rest.startswith(prefix + "_"):
            token_class = klass
            rest = rest[len(prefix):].lstrip("_")
            break
    if token_class is None:
        return None
    scope = "geo"
    long_ctx = False
    mode = "standard"
    tokens = [t for t in rest.split("_") if t]
    i = 0
    while i < len(tokens):
        token = tokens[i]
        if token == "global":
            scope = "global"
        elif token == "regional":
            scope = "geo"
        elif token == "long" and tokens[i + 1:i + 2] == ["ctx"]:
            long_ctx = True
            i += 1  # consume the `ctx` half of the pair as well
        elif token in MODES:
            mode = token
        elif _SNAKE_TTL.match(token) and token_class == "cache_write":
            # `cache_write_tokens_5m_...` is the default-TTL product, which IS the
            # base cache write; `_1h_` / `_30m_` are different products.
            if token != DEFAULT_CACHE_TTL:
                return EXCLUDED
        else:
            return None
        i += 1
    return region, RateDimension(token_class, scope, long_ctx, mode)


# --- Price List usage types (generation 4) ----------------------------------
# `USE1-xai.grok-4.6-mantle-input-tokens-global-standard`, and the older
# `USE1-nvidia.nemotron-super-3-120b-input-tokens-flex` without the `mantle` marker.
_USAGE_CLASSES = (
    ("input-tokens", "input"),
    ("output-tokens", "output"),
    ("cache-read-tokens", "cache_read"),
    ("cache-write-tokens", "cache_write"),
)
_USAGE_TTL = re.compile(r"^\d+[mh]$")


# The only segment allowed between a model id and its token-class marker. Anything
# else means the row is about a different product — a longer model id, a variant, a
# feature — and is refused. This is deliberately not a permissive "absorb lowercase
# segments" rule: `xai.grok-4` would then swallow every
# `USE1-xai.grok-4.6-mantle-input-tokens-...` row and charge Grok 4 traffic at Grok
# 4.6's rate. A model whose billed id differs from its registry id declares that id
# (`price_model_id` in the registry) instead of relying on a match that guesses.
_ALLOWED_ID_SUFFIX_SEGMENTS = frozenset(_load_id_suffix_segments())


def parse_price_list_usagetype(
    usagetype: str, model_id: str,
) -> Optional[tuple[str, RateDimension]] | _Excluded:
    """Parse one Price List `usagetype` for an exact billed model id.

    `model_id` must be the id the row is billed under, not merely a prefix of it: the
    billed spelling sometimes carries an extra segment (`qwen.qwen3-next-80b-a3b` is
    billed as `...-a3b-instruct`), and that difference is declared in the registry
    rather than absorbed here, because absorbing it cannot tell a variant of the same
    model from a different, dearer one.

    Three answers, same meanings as `parse_agreement_dimension`: a dimension, `EXCLUDED`
    for a product this gateway recognises and does not charge, and `None` for a shape it
    cannot read — which the caller counts, because a row that names one of OUR models and
    cannot be read is the signal a grammar changed.
    """
    if not isinstance(usagetype, str) or "-" not in usagetype:
        return None
    prefix, _, rest = usagetype.partition("-")
    region = BILLING_PREFIXES.get(prefix)
    if region is None or not rest:
        return None
    if not rest.startswith(model_id):
        return None
    remainder = rest[len(model_id):]
    # The id must end at a segment boundary. Without this, `xai.grok-4` matches the
    # start of `xai.grok-4.6-mantle-...`.
    if not remainder.startswith("-"):
        return None
    segments = [seg for seg in remainder.lstrip("-").split("-") if seg]
    if not segments:
        return None
    # From here the row is about a model we asked about, so an unreadable remainder is a
    # grammar problem rather than someone else's row, and the caller counts it.
    while segments and segments[0] in _ALLOWED_ID_SUFFIX_SEGMENTS:
        segments.pop(0)
    if not segments:
        return None
    rest = "-".join(segments)
    token_class = None
    for name, klass in _USAGE_CLASSES:
        if rest == name or rest.startswith(name + "-"):
            token_class = klass
            rest = rest[len(name):].lstrip("-")
            break
    if token_class is None:
        return None
    scope = "geo"
    mode = "standard"
    tokens = [t for t in rest.split("-") if t]
    for token in tokens:
        if token == "global":
            scope = "global"
        elif token in MODES:
            mode = token
        elif _USAGE_TTL.match(token) and token_class == "cache_write":
            # The default TTL IS the base cache write; a longer one is another product.
            # Same rule as the agreement grammar — stating it in one place and not the
            # other is how a leg ends up frozen on the floor while the provider publishes it.
            if token != DEFAULT_CACHE_TTL:
                return EXCLUDED
        else:
            return None
    return region, RateDimension(token_class, scope, mode=mode)


# --- unit normalisation ------------------------------------------------------
# Bedrock publishes the same kind of number in two units depending on which API
# and which offer it comes from: the agreement rate cards are per 1M tokens, the
# Price List rows for the same families are per 1K. A unit this table does not
# know is dropped rather than assumed, because assuming the wrong one is a
# 1000-fold pricing error.
_UNIT_MULTIPLIERS: dict[str, Decimal] = {
    "1m tokens": Decimal(1),
    "1k tokens": Decimal(1000),
    "units": Decimal(1),  # agreement rate cards report `Units`, priced per MTok.
}


def per_mtok(price: object, unit: str) -> Optional[Decimal]:
    """Normalise a published price to USD per million tokens, or `None`."""
    multiplier = _UNIT_MULTIPLIERS.get(str(unit).strip().lower())
    if multiplier is None:
        return None
    try:
        value = Decimal(str(price))
    except Exception:  # noqa: BLE001 — a non-numeric price is just unparseable.
        return None
    if value < 0:
        return None
    return value * multiplier


# --- selection --------------------------------------------------------------
# Cross-region inference profile prefixes. A model addressed through one of these
# is billed at the profile's scope, not at the plain in-region rate.
_GLOBAL_PROFILE_PREFIX = "global."
_GEO_PROFILE_PREFIXES = ("us.", "eu.", "apac.", "jp.", "au.", "ca.", "us-gov.")


def unknown_profile_prefix(bedrock_model_id: str) -> Optional[str]:
    """The leading segment when it looks like an inference-profile prefix this build does
    not know, else `None`.

    AWS keeps adding cross-region prefixes. An unrecognised one cannot be stripped on a
    guess — `xai.grok-4.6` has two dots and a bare provider id, so any "count the dots"
    rule mangles it — and it cannot be ignored either, because the price APIs reject a
    prefixed id and the model would drop off the feed silently. So it is NAMED: the caller
    reports it and asks for `price_model_id` on that registry entry, which settles the
    question with a fact instead of a heuristic.

    The shape checked here is a short alphabetic first segment followed by a
    provider-qualified remainder (`mx.anthropic.claude-opus-5`), which is what a profile id
    looks like and what a bare `provider.model` id does not.
    """
    head, sep, rest = bedrock_model_id.partition(".")
    if not sep or not rest or "." not in rest:
        return None
    if bedrock_model_id.startswith(_GLOBAL_PROFILE_PREFIX) or \
            bedrock_model_id.startswith(_GEO_PROFILE_PREFIXES):
        return None
    # `xai.grok-4.6`: the remainder's dot belongs to a version number, not to a provider
    # namespace, so this is a bare id rather than a prefixed one.
    provider, _, tail = rest.partition(".")
    if not provider.replace("-", "").isalpha() or not tail:
        return None
    if not head.replace("-", "").isalpha() or len(head) > 8:
        return None
    return head


def scope_for_model_id(bedrock_model_id: str) -> Optional[str]:
    """Which price scope a model id is billed at, or `None` when it cannot be told.

    `None` is not an error: the caller then takes the more expensive of the two
    scopes, because guessing the cheaper one under-charges. An id with a prefix this
    build does not recognise deliberately lands there rather than being assumed
    in-region.
    """
    if bedrock_model_id.startswith(_GLOBAL_PROFILE_PREFIX):
        return "global"
    if bedrock_model_id.startswith(_GEO_PROFILE_PREFIXES):
        return "geo"
    if unknown_profile_prefix(bedrock_model_id) is not None:
        # A prefix shaped like a profile but not on the known list: which scope it bills
        # at is exactly what we cannot tell.
        return None
    if "." in bedrock_model_id:
        # A bare provider-qualified id (`anthropic.claude-...`) is invoked in one
        # region and billed at that region's in-region rate.
        return "geo"
    return None


def base_model_id(bedrock_model_id: str) -> str:
    """The provider's own model id, with any inference-profile prefix removed.

    Both price APIs key on the bare id: `list-foundation-model-agreement-offers`
    rejects `us.anthropic.claude-opus-5` as an invalid identifier and answers for
    `anthropic.claude-opus-5`, and the Price List embeds the bare id in its usage
    types. The prefix is not lost — it is what `scope_for_model_id` reads to decide
    which of the published scopes the traffic is actually billed at.

    A prefix this build does not recognise is NOT stripped on a guess: `xai.grok-4.6` is
    a bare id whose second dot belongs to a version number, and a "strip the first
    segment" rule would turn it into `grok-4.6` and stop matching anything. Such an id is
    reported by `unknown_profile_prefix` so the registry entry can settle it with
    `price_model_id`, and `scope_for_model_id` calls its scope unknown, which prices it at
    the dearer of the two.
    """
    if bedrock_model_id.startswith(_GLOBAL_PROFILE_PREFIX):
        return bedrock_model_id[len(_GLOBAL_PROFILE_PREFIX):]
    for prefix in _GEO_PROFILE_PREFIXES:
        if bedrock_model_id.startswith(prefix):
            return bedrock_model_id[len(prefix):]
    return bedrock_model_id


@dataclass(frozen=True)
class Selection:
    """What a card can say about one model, and what it says nothing about."""

    # token class -> USD per million tokens. Only the classes that resolved.
    rates: dict[str, Decimal]
    # Classes this provider does not price for this model AT ALL, in any region or
    # scope. The caller fills these from the layer below.
    absent: frozenset[str]
    # Classes that resolved only by looking outside the region or scope that was
    # asked for, priced at the dearest match. Real and common: Claude Opus 5
    # publishes its cache legs in-region only, so a deployment addressing it through
    # a `global.` profile would otherwise have no cache rate at all and the whole
    # model would fall to the floor — which for the legacy Opus row is a 3x
    # over-charge. Widening keeps the model on live prices in the over-charging
    # direction and is REPORTED, because a leg that has to be widened is a sign the
    # routing assumption and the price list disagree.
    widened: frozenset[str] = frozenset()


def select(
    card: Mapping[tuple[Optional[str], RateDimension], Decimal],
    *,
    regions: Iterable[str],
    scope: Optional[str],
) -> Optional[Selection]:
    """Pick one USD-per-MTok value per token class out of a parsed card.

    Returns `None` — refuse this model — only when input or output does not resolve at
    all. Without those two there is nothing to charge a request with, and taking either
    from a long-context or batch number would price ordinary traffic at another product's
    rate.

    Every other unresolved class is answered rather than refused, in the over-charging
    direction, and labelled so the caller can report it:

    - `absent` — the provider prices this class nowhere (Nemotron and Qwen publish no
      cache rates; xAI publishes a cache read but no cache write). The caller fills the
      leg from the layer below, so the model is not thrown onto the floor wholesale —
      which for Nemotron would mean charging $5/MTok for input that costs $0.15 — and no
      leg is ever invented as zero.
    - `widened` — the class is priced, but not for the region or scope asked for, so the
      dearest published number is used instead.

    Within a class the value is the maximum over the candidate regions and the
    requested scope. `max` rather than "the entry's own region" because a Converse
    request can fail over mid-flight, and a reservation priced at the cheaper region
    would settle above what it admitted.
    """
    scopes = (scope,) if scope else SCOPES
    wanted_regions = {r for r in regions if r}
    rates: dict[str, Decimal] = {}
    absent: set[str] = set()
    widened: set[str] = set()
    for token_class in TOKEN_CLASSES:
        exact: Optional[Decimal] = None
        anywhere: Optional[Decimal] = None
        for (region, slot), value in card.items():
            if slot.token_class != token_class:
                continue
            if slot.long_ctx or slot.mode != "standard":
                # A long-context or non-standard-tier number is a different product,
                # so it does not even count as this class being priced.
                continue
            if anywhere is None or value > anywhere:
                anywhere = value
            if slot.scope not in scopes:
                continue
            # A region-free card (the OpenAI shape) prices every region alike, so it
            # answers for any candidate region.
            if region is not None and wanted_regions and region not in wanted_regions:
                continue
            if exact is None or value > exact:
                exact = value
        if exact is not None:
            rates[token_class] = exact
        elif anywhere is not None:
            # Priced, but not for the scope or region asked for. Take the dearest
            # published number rather than refusing the model: refusing sends every
            # leg to the floor, which is the larger error in both directions.
            rates[token_class] = anywhere
            widened.add(token_class)
        else:
            absent.add(token_class)
    if "input" not in rates or "output" not in rates:
        return None
    return Selection(rates=rates, absent=frozenset(absent),
                    widened=frozenset(widened))
