//! `stratoclave codex -- [args]` subcommand.
//!
//! Launches OpenAI codex as a child process with a temporary
//! `~/.codex/config.toml` (delivered via the `CODEX_CONFIG` env var) so
//! every `/openai/v1/responses` call flows through stratoclave instead
//! of going directly to bedrock-mantle.
//!
//! Like `stratoclave claude`, this wrapper:
//!
//!   1. Mints an ephemeral, `responses:send`-only `sk-stratoclave-*`
//!      key via `mvp::ephemeral_key::mint_ephemeral_key_scoped`.
//!   2. Writes a temp TOML pointing codex at the stratoclave OpenAI base
//!      URL (e.g. `https://xxx.cloudfront.net/openai/v1`) and a env-key
//!      reference for the bearer (`STRATOCLAVE_OPENAI_KEY`).
//!   3. Hands codex the temp file via `CODEX_CONFIG`, sets the env-key,
//!      and revokes the wrapper key on exit through
//!      `ChildLauncher::run_with_revoke`.
//!
//! The user's persistent `~/.codex/config.toml` is **never** mutated by
//! this subcommand. `stratoclave setup --codex` is the opt-in path that
//! patches that file (with backup + prompt).

use anyhow::{Context, Result};
use std::io::Write;
use std::process::ExitCode;

use tempfile::NamedTempFile;

use super::child_launcher::ChildLauncher;
use super::config::MvpConfig;
use super::ephemeral_key::mint_ephemeral_key_scoped;
use super::tokens::load as load_tokens;

pub async fn run(args: &[String], model_override: Option<&str>) -> Result<ExitCode> {
    let config = MvpConfig::load()?;
    let tokens = load_tokens()?;

    let model = model_override
        .map(String::from)
        .unwrap_or_else(|| config.default_codex_model.clone());

    let base_url = format!(
        "{}{}",
        config.api_endpoint.trim_end_matches('/'),
        config
            .codex_openai_base_path
            .as_deref()
            .unwrap_or("/openai/v1"),
    );

    // Mint the scoped wrapper key first; on failure we never spawn the
    // child and never need to revoke.
    let key = mint_ephemeral_key_scoped(
        &config.api_endpoint,
        &tokens.access_token,
        "stratoclave-codex-wrapper",
        &["responses:send"],
    )
    .await
    .context("Failed to mint ephemeral wrapper key for codex")?;

    let temp_config = write_temp_codex_config(&base_url, &model)
        .context("Failed to write temporary codex config.toml")?;

    eprintln!(
        "[INFO] Launching codex via Stratoclave proxy (base_url={}, model={}, key={})",
        base_url, model, key.key_id
    );
    eprintln!(
        "[INFO] Child process uses an ephemeral responses-only API key; \
         the Cognito bearer is not exported and the user's ~/.codex/config.toml \
         is untouched."
    );

    let result = ChildLauncher::new("codex")
        .env("CODEX_CONFIG", temp_config.path())
        .env("STRATOCLAVE_OPENAI_KEY", &key.plaintext_key)
        .scrub_stratoclave_tokens()
        .scrub_aws_identity()
        .run_with_revoke(
            args,
            &config.api_endpoint,
            &tokens.access_token,
            &key.key_id,
        )
        .await;

    // Drop the temp file deterministically so it does not survive the
    // wrapper exit (NamedTempFile auto-deletes on Drop, but the explicit
    // close keeps the failure mode explicit if the FS rejects it).
    drop(temp_config);
    result
}

fn write_temp_codex_config(base_url: &str, model: &str) -> Result<NamedTempFile> {
    let mut f = NamedTempFile::new().context("NamedTempFile::new")?;
    let body = format!(
        r#"# Auto-generated by `stratoclave codex` — do not edit.
# This file is the value of CODEX_CONFIG for a single child invocation
# and is deleted when the wrapper exits.

model_provider = "stratoclave"
model = "{model}"

[model_providers.stratoclave]
name                   = "Stratoclave (OpenAI via Bedrock)"
base_url               = "{base_url}"
wire_api               = "responses"
env_key                = "STRATOCLAVE_OPENAI_KEY"
request_max_retries    = 3
stream_max_retries     = 5
stream_idle_timeout_ms = 600000
supports_websockets    = false
"#,
    );
    f.write_all(body.as_bytes())
        .context("write temp codex config")?;
    f.flush().context("flush temp codex config")?;
    Ok(f)
}
