//! Where `stratoclave codex` puts `CODEX_HOME`.
//!
//! `CODEX_HOME` holds two different things: the configuration codex reads, and
//! the state codex writes. Pointing it at a throwaway temp directory keeps the
//! user's `~/.codex/config.toml` out of a proxied run — which is the point — but
//! it also throws away everything codex records:
//!
//!   * `sessions/`, the rollout transcripts `codex resume` reads. Every
//!     conversation held through the gateway is unrecoverable the moment the
//!     wrapper exits.
//!   * `history.jsonl` and `log/`.
//!   * the per-directory trust answers codex writes into `config.toml`, so it
//!     re-asks "do you trust the contents of this directory?" on every launch.
//!
//! Exporting `CODEX_HOME` yourself does not help: the wrapper owns that variable.
//!
//! So the durable directory *is* `CODEX_HOME` (default
//! `~/.stratoclave/codex-state`, never `~/.codex`), and the only file the wrapper
//! owns inside it is `config.toml`, rewritten before each run. State that codex
//! invents later — a new directory, a new index file — persists automatically,
//! because persistence is the default and this module never enumerates what
//! codex may write. Keys inside `config.toml` that the wrapper does not manage
//! (trust answers among them) are carried across the rewrite.
//!
//! `--ephemeral-codex-state` restores the old behaviour: a temp `CODEX_HOME`
//! deleted on exit, nothing kept.
//!
//! The proper fix belongs upstream: codex should separate its config directory
//! from its state directory. This module can be deleted the day it does.

use anyhow::{anyhow, Context, Result};
use std::fs;
use std::path::{Path, PathBuf};

use tempfile::TempDir;

/// Top-level `config.toml` keys the wrapper owns, i.e. the ones it regenerates and
/// therefore does not carry over. Everything else found in an existing file is
/// preserved verbatim, so codex can add state without this list needing an update.
///
/// The list is also the provider boundary: anything that could point codex at a
/// different provider belongs here, or a leftover key could take the run off the
/// gateway while the wrapper still reports it as proxied.
const WRAPPER_OWNED_KEYS: &[&str] = &[
    "model_provider",
    "model",
    "web_search",
    "project_root_markers",
    "model_context_window",
    "model_providers",
    // Not carried over even though codex owns it: a profile can name another
    // `model_provider`, so preserving one would let `--profile` route the run
    // straight to a provider while the wrapper still claims it is proxied.
    "profiles",
];

/// First bytes of a `config.toml` the wrapper generated. Used to tell "ours" from
/// a file that belonged to someone else before `--codex-state-dir` pointed here.
pub const GENERATED_MARKER: &str = "# Auto-generated by `stratoclave codex`";

/// Keys carried over from a previous run, split by TOML shape so the caller can
/// place them on the correct side of its own table headers.
#[derive(Debug, Default, PartialEq, Eq)]
pub struct PreservedConfig {
    /// Bare `key = value` lines. Must be emitted BEFORE any table header.
    pub top_level: String,
    /// `[table]` sections. Must be emitted AFTER the caller's own tables.
    pub tables: String,
}

/// Serialize a sub-table for inclusion in the generated config, with a comment
/// saying where it came from. Empty input renders as an empty string.
fn render_preserved(table: &toml::Table) -> String {
    if table.is_empty() {
        return String::new();
    }
    match toml::to_string(table) {
        Ok(s) => format!(
            "\n# Carried over from the previous run (directory trust and other\n\
             # codex-owned keys). The wrapper only rewrites the keys it manages.\n{s}"
        ),
        Err(e) => {
            eprintln!("[WARN] Could not re-serialize preserved codex config keys: {e}");
            String::new()
        }
    }
}

/// A prepared `CODEX_HOME`.
#[derive(Debug)]
pub struct CodexHome {
    path: PathBuf,
    /// Present only for `--ephemeral-codex-state`; dropping it deletes the dir.
    /// Held so the directory outlives the child process.
    temp: Option<TempDir>,
    /// Exclusive claim on a durable state directory, released when this drops.
    ///
    /// `config.toml` carries the run's model and its x-sc-* attribution headers,
    /// and codex reads it at startup. Two runs sharing a directory could
    /// therefore hand each other's model or billing group to the wrong child, so
    /// only one run at a time may own a durable directory. Held, never read.
    _lock: Option<RunLock>,
}

/// Advisory lock on a durable state directory, held for the life of the run.
///
/// The lock lives on an open file descriptor (`flock`), not on the existence of a
/// file. That distinction is the point: a lock file left behind by a crashed run
/// has to be aged out by guesswork, and two runs that both decide it is stale can
/// hand it to each other. A kernel-held lock is released when the process dies,
/// however it dies, so there is no staleness to judge and no window to race.
#[derive(Debug)]
struct RunLock {
    /// Held open for the lifetime of the run; closing it releases the lock.
    _file: fs::File,
}

impl CodexHome {
    /// Prepare the directory codex will use as `CODEX_HOME`.
    ///
    /// `flag` is `--codex-state-dir`; `STRATOCLAVE_CODEX_STATE_DIR` is the
    /// fallback, then `~/.stratoclave/codex-state`. Relative paths are resolved
    /// against the current directory, because the child may run with a different
    /// working directory than the launcher.
    pub fn prepare(flag: Option<&str>, ephemeral: bool) -> Result<Self> {
        if ephemeral {
            return Self::ephemeral();
        }
        let root = resolve_state_dir(flag)?;
        reject_user_codex_home(&root)?;
        fs::create_dir_all(&root)
            .with_context(|| format!("create codex state dir {}", root.display()))?;
        // The directory now exists, so a `..` in the input has become resolvable:
        // re-check against the real path before writing anything into it.
        reject_user_codex_home(&fs::canonicalize(&root).unwrap_or_else(|_| root.clone()))?;
        // Rollout transcripts are the conversation itself, so a directory we
        // cannot restrict is a directory we decline to write conversations into.
        // On a platform without Unix permission bits that is every directory, so
        // durable state is Unix-only rather than silently unprotected.
        #[cfg(not(unix))]
        {
            eprintln!(
                "[WARN] Durable codex state needs owner-only directory permissions, which \
                 this platform does not provide; this run keeps no state. Use \
                 --ephemeral-codex-state to silence this."
            );
            return Self::ephemeral();
        }
        #[cfg(unix)]
        restrict_dir(&root)?;
        #[cfg(unix)]
        match RunLock::acquire(&root)? {
            Some(lock) => Ok(Self {
                path: root,
                temp: None,
                _lock: Some(lock),
            }),
            None => {
                // Another run owns the directory. Falling back to a temp
                // CODEX_HOME keeps concurrent work possible; mixing two runs'
                // config would instead mis-attribute billing.
                eprintln!(
                    "[WARN] {} is in use by another `stratoclave codex` run, so this run \
                     keeps no state (sessions, history, trust). Pass a different \
                     --codex-state-dir to persist concurrent runs separately.",
                    root.display()
                );
                Self::ephemeral()
            }
        }
    }

    fn ephemeral() -> Result<Self> {
        let temp = TempDir::new().context("TempDir::new for CODEX_HOME")?;
        Ok(Self {
            path: temp.path().to_path_buf(),
            temp: Some(temp),
            _lock: None,
        })
    }

    pub fn path(&self) -> &Path {
        &self.path
    }

    /// True when state survives the run (i.e. not `--ephemeral-codex-state`).
    pub fn is_durable(&self) -> bool {
        self.temp.is_none()
    }

    /// The keys of an existing `config.toml` that the wrapper does not own —
    /// directory-trust answers among them — split by TOML shape.
    ///
    /// The split is not cosmetic. TOML binds a bare key to the table header above
    /// it, so a scalar emitted after `[model_providers.stratoclave]` becomes
    /// `model_providers.stratoclave.<key>`. Carrying `approval_policy` or
    /// `sandbox_mode` that way would silently move a security setting into the
    /// provider table, where codex never reads it. Scalars must therefore be
    /// placed before the first table header and tables after it, which is what
    /// the two fields are for.
    ///
    /// A `config.toml` that fails to parse is reported and skipped rather than
    /// propagated: a hand-edited or truncated file must not take the next run
    /// down with it.
    fn preserved_config(existing: Option<&[u8]>, path: &Path) -> PreservedConfig {
        let Some(bytes) = existing else {
            return PreservedConfig::default();
        };
        let body = match std::str::from_utf8(bytes) {
            Ok(b) => b,
            Err(_) => {
                eprintln!(
                    "[WARN] {} is not valid UTF-8, so no keys can be carried over from it \
                     (a copy was saved next to it).",
                    path.display()
                );
                return PreservedConfig::default();
            }
        };
        let mut table = match toml::from_str::<toml::Table>(body) {
            Ok(t) => t,
            Err(e) => {
                eprintln!(
                    "[WARN] Ignoring unparseable {}: {e}. Directory-trust answers \
                     recorded there are lost, so codex may ask again.",
                    path.display()
                );
                return PreservedConfig::default();
            }
        };
        for key in WRAPPER_OWNED_KEYS {
            table.remove(*key);
        }
        let mut scalars = toml::Table::new();
        let mut tables = toml::Table::new();
        for (k, v) in table {
            if v.is_table() {
                tables.insert(k, v);
            } else {
                scalars.insert(k, v);
            }
        }
        PreservedConfig {
            top_level: render_preserved(&scalars),
            tables: render_preserved(&tables),
        }
    }

    /// Rewrite `config.toml`, preserving the codex-owned keys already in it.
    ///
    /// `render` receives those keys and returns the full file. The merge is not
    /// something a caller can forget: taking a renderer rather than a finished
    /// string is what keeps a future call site from silently dropping the user's
    /// directory-trust answers.
    ///
    /// The write is atomic, so a codex starting concurrently never reads a
    /// half-written file, and a body that does not parse is rejected — the
    /// wrapper would otherwise hand codex a config it silently ignores.
    pub fn write_config(&self, render: impl FnOnce(&PreservedConfig) -> String) -> Result<()> {
        let final_path = self.path.join("config.toml");
        // Read the bytes once, and only treat NotFound as "there is nothing here".
        // A permission error or a non-UTF-8 file must not be mistaken for absence:
        // that mistake is what would let the rewrite proceed with no backup.
        let existing = match fs::read(&final_path) {
            Ok(bytes) => Some(bytes),
            Err(e) if e.kind() == std::io::ErrorKind::NotFound => None,
            Err(e) => {
                return Err(e).with_context(|| {
                    format!(
                        "read {} before rewriting it (refusing to overwrite a file it \
                         cannot read)",
                        final_path.display()
                    )
                })
            }
        };
        self.back_up_foreign_config(&final_path, existing.as_deref())?;
        let preserved = Self::preserved_config(existing.as_deref(), &final_path);
        let body = render(&preserved);
        toml::from_str::<toml::Table>(&body)
            .context("generated codex config.toml is not valid TOML")?;
        // A unique temp name, not a fixed `config.toml.tmp`: two runs sharing a
        // state directory would otherwise write to the same scratch path and
        // could splice each other's bytes, or lose the rename to ENOENT.
        let mut tmp = tempfile::Builder::new()
            .prefix(".config.toml.")
            .suffix(".tmp")
            .tempfile_in(&self.path)
            .with_context(|| format!("create temp config in {}", self.path.display()))?;
        use std::io::Write;
        tmp.write_all(body.as_bytes())
            .with_context(|| format!("write temp config in {}", self.path.display()))?;
        tmp.flush().ok();
        tmp.persist(&final_path)
            .map_err(|e| e.error)
            .with_context(|| format!("persist {}", final_path.display()))?;
        Ok(())
    }

    /// Copy a `config.toml` the wrapper did not author to `config.toml.bak`, once.
    ///
    /// Only reachable when someone points `--codex-state-dir` at a directory that
    /// already holds a codex config. The rewrite drops comments and the keys the
    /// wrapper owns, so the copy is what makes that recoverable.
    fn back_up_foreign_config(&self, config_path: &Path, existing: Option<&[u8]>) -> Result<()> {
        let Some(existing) = existing else {
            return Ok(());
        };
        if existing.starts_with(GENERATED_MARKER.as_bytes()) {
            return Ok(());
        }
        let backup = self.path.join("config.toml.bak");
        if backup.is_file() {
            // Already saved on an earlier run; keep the original, not a copy of
            // our own rewrite.
            return Ok(());
        }
        // Fail closed: the rewrite is destructive (comments and wrapper-owned
        // keys go away), so refusing to proceed without a recovery copy is the
        // only honest behaviour.
        fs::copy(config_path, &backup).with_context(|| {
            format!(
                "back up {} to {} before rewriting it (refusing to overwrite a config \
                 stratoclave did not write without a copy; move or delete it, or point \
                 --codex-state-dir somewhere else)",
                config_path.display(),
                backup.display()
            )
        })?;
        eprintln!(
            "[WARN] {} was not written by stratoclave; copied it to {} before rewriting \
             (the rewrite drops comments and wrapper-owned keys).",
            config_path.display(),
            backup.display()
        );
        Ok(())
    }
}

impl RunLock {
    /// Take the lock on `<root>/run.lock`. `Ok(None)` means a live run holds it.
    ///
    /// The file is created if absent and never deleted: ownership is the `flock`,
    /// not the file, so a leftover file is inert and there is nothing to clean up
    /// or age out.
    #[cfg(unix)]
    fn acquire(root: &Path) -> Result<Option<Self>> {
        use std::os::unix::io::AsRawFd;
        let path = root.join("run.lock");
        let file = fs::OpenOptions::new()
            .create(true)
            .truncate(false)
            .write(true)
            .open(&path)
            .with_context(|| format!("open lock {}", path.display()))?;
        // The crate denies `unsafe_code`; this is the same narrow exemption the
        // repo already uses for small libc calls. SAFETY: the fd is owned by
        // `file`, which outlives the call, and `flock` only reads it.
        #[allow(unsafe_code)]
        let rc = unsafe { libc::flock(file.as_raw_fd(), libc::LOCK_EX | libc::LOCK_NB) };
        if rc == 0 {
            return Ok(Some(Self { _file: file }));
        }
        let err = std::io::Error::last_os_error();
        match err.raw_os_error() {
            Some(code) if code == libc::EWOULDBLOCK || code == libc::EAGAIN => Ok(None),
            _ => Err(err).with_context(|| format!("lock {}", path.display())),
        }
    }
}

/// Resolve the durable state directory to an absolute path.
///
/// An empty `STRATOCLAVE_CODEX_STATE_DIR` counts as unset: `var_os` reports it as
/// present, and treating `""` as a path yields a directory named after nothing.
fn resolve_state_dir(flag: Option<&str>) -> Result<PathBuf> {
    let from_env = std::env::var_os("STRATOCLAVE_CODEX_STATE_DIR")
        .map(PathBuf::from)
        .filter(|p| !p.as_os_str().is_empty());
    let chosen = flag
        .filter(|s| !s.is_empty())
        .map(PathBuf::from)
        .or(from_env)
        .or_else(|| dirs::home_dir().map(|h| h.join(".stratoclave").join("codex-state")))
        .ok_or_else(|| {
            anyhow!(
                "could not determine a codex state directory: no --codex-state-dir, \
                 no STRATOCLAVE_CODEX_STATE_DIR, and no home directory"
            )
        })?;
    // `std::path::absolute` also drops `.` components, so the path we print and
    // hand to the child reads like a path rather than `/cwd/./state`.
    std::path::absolute(&chosen)
        .with_context(|| format!("resolve codex state dir {}", chosen.display()))
}

/// Refuse to treat the user's own codex home as the state directory.
///
/// The wrapper rewrites `config.toml` in whatever directory it is given, dropping
/// comments and the keys it manages. Doing that to `~/.codex` would delete the
/// user's custom `model_providers`, their `model`, and their
/// `project_root_markers` with no warning — the exact file every doc promises is
/// never touched.
fn reject_user_codex_home(root: &Path) -> Result<()> {
    let mut forbidden: Vec<PathBuf> = Vec::new();
    if let Some(home) = dirs::home_dir() {
        forbidden.push(home.join(".codex"));
    }
    // Whatever the user had exported before the wrapper overrode it for the child.
    if let Some(env_home) = std::env::var_os("CODEX_HOME") {
        if !env_home.is_empty() {
            forbidden.push(PathBuf::from(env_home));
        }
    }
    // Fold `.` / `..` without touching the filesystem: the target may not exist
    // yet, in which case `canonicalize` fails and a raw comparison would let
    // `~/.codex/anything/..` through — the check would pass and the rewrite would
    // still land on the user's real config.
    let canonical = |p: &Path| fs::canonicalize(p).unwrap_or_else(|_| logical_normalize(p));
    let root_c = canonical(root);
    for f in forbidden {
        if canonical(&f) == root_c {
            return Err(anyhow!(
                "refusing to use {} as the codex state directory: `stratoclave codex` \
                 rewrites config.toml there, which would drop your own codex settings. \
                 Pick a different --codex-state-dir (the default is \
                 ~/.stratoclave/codex-state).",
                root.display()
            ));
        }
    }
    Ok(())
}

/// Restrict the state directory to its owner.
///
/// Errors rather than warning: this directory now holds conversation
/// transcripts, so continuing after a failed `chmod` would persist prompts into a
/// directory whose permissions are unknown.
#[cfg(unix)]
fn restrict_dir(dir: &Path) -> Result<()> {
    use std::os::unix::fs::PermissionsExt;
    fs::set_permissions(dir, fs::Permissions::from_mode(0o700)).with_context(|| {
        format!(
            "restrict {} to owner-only (it holds conversation transcripts)",
            dir.display()
        )
    })
}

/// Fold `.` and `..` components lexically, without consulting the filesystem.
fn logical_normalize(p: &Path) -> PathBuf {
    let mut out = PathBuf::new();
    for c in p.components() {
        match c {
            std::path::Component::CurDir => {}
            std::path::Component::ParentDir => {
                out.pop();
            }
            other => out.push(other.as_os_str()),
        }
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    /// `STRATOCLAVE_CODEX_STATE_DIR` is process-global, so the tests that touch it
    /// run under one lock.
    static ENV_LOCK: std::sync::Mutex<()> = std::sync::Mutex::new(());

    /// Read what the tests need: the keys a rewrite would carry over from the file
    /// currently in the directory.
    fn preserved_of(home: &CodexHome) -> PreservedConfig {
        let path = home.path().join("config.toml");
        let bytes = fs::read(&path).ok();
        CodexHome::preserved_config(bytes.as_deref(), &path)
    }

    fn home_with(dir: &Path) -> CodexHome {
        CodexHome {
            path: dir.to_path_buf(),
            temp: None,
            _lock: None,
        }
    }

    #[test]
    fn ephemeral_home_is_a_temp_dir_that_is_not_durable() {
        let home = CodexHome::prepare(None, true).expect("prepare");
        assert!(home.path().is_dir());
        assert!(!home.is_durable());
    }

    // A relative --codex-state-dir must not stay relative: the child can run with
    // a different cwd, and a relative CODEX_HOME would silently point somewhere
    // else (or nowhere).
    #[test]
    fn relative_state_dir_is_resolved_against_cwd() {
        let resolved = resolve_state_dir(Some("relative/state")).expect("resolve");
        assert!(resolved.is_absolute(), "got {}", resolved.display());
        assert!(resolved.ends_with("relative/state"));
    }

    #[test]
    fn empty_flag_and_empty_env_fall_through_to_the_default() {
        let _guard = ENV_LOCK.lock().unwrap();
        std::env::set_var("STRATOCLAVE_CODEX_STATE_DIR", "");
        let resolved = resolve_state_dir(Some("")).expect("resolve");
        std::env::remove_var("STRATOCLAVE_CODEX_STATE_DIR");
        assert!(
            resolved.ends_with(".stratoclave/codex-state"),
            "got {}",
            resolved.display()
        );
    }

    #[test]
    fn env_var_is_used_when_no_flag_is_given() {
        let _guard = ENV_LOCK.lock().unwrap();
        std::env::set_var("STRATOCLAVE_CODEX_STATE_DIR", "/tmp/sc-codex-env");
        let resolved = resolve_state_dir(None).expect("resolve");
        std::env::remove_var("STRATOCLAVE_CODEX_STATE_DIR");
        assert_eq!(resolved, PathBuf::from("/tmp/sc-codex-env"));
    }

    #[test]
    fn trust_answers_are_preserved_as_tables() {
        let dir = TempDir::new().unwrap();
        let home = home_with(dir.path());
        // What codex leaves behind after the user answers the trust prompt.
        home.write_config(|_| "model = \"openai.gpt-5.4\"\n\n[projects.\"/Users/me/repo\"]\ntrust_level = \"trusted\"\n".to_string())
            .unwrap();

        let preserved = preserved_of(&home);
        assert!(
            preserved.tables.contains("[projects."),
            "got: {preserved:?}"
        );
        assert!(preserved.top_level.is_empty(), "got: {preserved:?}");
        // The wrapper's own key is regenerated, never carried over.
        assert!(!preserved.tables.contains("model ="), "got: {preserved:?}");
    }

    // The reason `PreservedConfig` has two fields: TOML binds a bare key to the
    // table header above it. A scalar carried over after a table header would land
    // inside that table, so `approval_policy` would become
    // `model_providers.stratoclave.approval_policy` and codex would run with its
    // default sandbox instead of the user's.
    #[test]
    fn scalars_and_tables_are_split_so_they_can_be_placed_correctly() {
        let dir = TempDir::new().unwrap();
        let home = home_with(dir.path());
        home.write_config(|_| "model = \"m\"\napproval_policy = \"never\"\nsandbox_mode = \"read-only\"\n\n[projects.\"/repo\"]\ntrust_level = \"trusted\"\n".to_string())
            .unwrap();

        let preserved = preserved_of(&home);
        assert!(preserved.top_level.contains("approval_policy = \"never\""));
        assert!(preserved.top_level.contains("sandbox_mode = \"read-only\""));
        assert!(!preserved.top_level.contains("[projects"));
        assert!(preserved.tables.contains("[projects.\"/repo\"]"));
        assert!(!preserved.tables.contains("approval_policy"));

        // Emitted in the documented order — scalars before the caller's table,
        // tables after — the values keep their top-level identity.
        let assembled = format!(
            "model = \"other\"\n{}\n[model_providers.sc]\nname = \"x\"\n{}",
            preserved.top_level, preserved.tables
        );
        let parsed: toml::Table = toml::from_str(&assembled).expect("must parse: {assembled}");
        assert_eq!(parsed["approval_policy"].as_str(), Some("never"));
        assert_eq!(parsed["sandbox_mode"].as_str(), Some("read-only"));
        assert!(parsed["model_providers"]["sc"]
            .get("approval_policy")
            .is_none());
    }

    // Persistence must be default-open: a key codex invents later has to survive
    // even though this module knows nothing about it.
    #[test]
    fn unknown_codex_keys_are_preserved_too() {
        let dir = TempDir::new().unwrap();
        let home = home_with(dir.path());
        home.write_config(|_| {
            "model = \"m\"\nsome_future_state = 42\n\n[tui]\nnux_seen = true\n".to_string()
        })
        .unwrap();
        let preserved = preserved_of(&home);
        assert!(
            preserved.top_level.contains("some_future_state = 42"),
            "got: {preserved:?}"
        );
        assert!(preserved.tables.contains("[tui]"), "got: {preserved:?}");
        assert!(
            !preserved.top_level.contains("model ="),
            "wrapper-owned key leaked: {preserved:?}"
        );
    }

    // A profile can name another `model_provider`, so carrying one over would let
    // `--profile` take the run off the gateway while the wrapper still says it is
    // proxied. Provider-redirecting keys are the wrapper's, not the user's.
    #[test]
    fn a_leftover_profile_is_not_carried_over() {
        let dir = TempDir::new().unwrap();
        let home = home_with(dir.path());
        home.write_config(|_| {
            "model = \"m\"\n\n[profiles.direct]\nmodel_provider = \"openai\"\n".to_string()
        })
        .unwrap();

        let mut seen = String::new();
        home.write_config(|preserved| {
            seen = format!("{}{}", preserved.top_level, preserved.tables);
            format!("{GENERATED_MARKER}\nmodel = \"m2\"\n{}", preserved.tables)
        })
        .unwrap();
        assert!(!seen.contains("profiles"), "a profile must not survive: {seen}");
    }

    // "Cannot read it" is not "it is not there". Treating the two alike is what
    // would let the rewrite destroy a file it never managed to copy.
    #[test]
    fn a_config_that_cannot_be_parsed_as_text_is_still_backed_up() {
        let dir = TempDir::new().unwrap();
        let home = home_with(dir.path());
        // Invalid UTF-8: readable bytes, unusable as TOML.
        fs::write(dir.path().join("config.toml"), [0xff, 0xfe, 0x00, 0x41]).unwrap();

        home.write_config(|_| format!("{GENERATED_MARKER}\nmodel = \"m\"\n"))
            .unwrap();
        let backup = fs::read(dir.path().join("config.toml.bak")).expect("backup");
        assert_eq!(backup, vec![0xff, 0xfe, 0x00, 0x41]);
    }

    #[test]
    fn unparseable_existing_config_is_skipped_not_propagated() {
        let dir = TempDir::new().unwrap();
        fs::write(dir.path().join("config.toml"), "this is not = = toml").unwrap();
        assert_eq!(
            preserved_of(&home_with(dir.path())),
            PreservedConfig::default()
        );
    }

    // Pointing --codex-state-dir at the user's own codex home would rewrite the
    // file every doc promises is never touched.
    #[test]
    fn the_users_codex_home_is_refused() {
        let home = dirs::home_dir().expect("home dir");
        let err = CodexHome::prepare(Some(home.join(".codex").to_str().unwrap()), false)
            .expect_err("must refuse ~/.codex");
        assert!(
            format!("{err:#}").contains("refusing to use"),
            "got: {err:#}"
        );
    }

    // A config that was not written by the wrapper is recoverable after the
    // rewrite drops its comments and wrapper-owned keys.
    #[test]
    fn a_foreign_config_is_backed_up_once_before_the_rewrite() {
        let dir = TempDir::new().unwrap();
        let home = home_with(dir.path());
        fs::write(
            dir.path().join("config.toml"),
            "# my own notes\nmodel = \"mine\"\n",
        )
        .unwrap();

        home.write_config(|_| format!("{GENERATED_MARKER}\nmodel = \"generated\"\n"))
            .unwrap();
        let backup = fs::read_to_string(dir.path().join("config.toml.bak")).expect("backup");
        assert!(backup.contains("# my own notes"));

        // Rewriting our own file again must not overwrite that backup.
        home.write_config(|_| format!("{GENERATED_MARKER}\nmodel = \"generated2\"\n"))
            .unwrap();
        assert!(fs::read_to_string(dir.path().join("config.toml.bak"))
            .unwrap()
            .contains("# my own notes"));
    }

    // Two runs sharing a state dir must not write to the same scratch path.
    #[test]
    fn temp_config_files_do_not_collide_and_leave_no_residue() {
        let dir = TempDir::new().unwrap();
        let home = home_with(dir.path());
        home.write_config(|_| format!("{GENERATED_MARKER}\nmodel = \"a\"\n"))
            .unwrap();
        home.write_config(|_| format!("{GENERATED_MARKER}\nmodel = \"b\"\n"))
            .unwrap();
        let leftovers: Vec<_> = fs::read_dir(dir.path())
            .unwrap()
            .filter_map(|e| e.ok())
            .map(|e| e.file_name().to_string_lossy().to_string())
            .filter(|n| n.ends_with(".tmp"))
            .collect();
        assert!(
            leftovers.is_empty(),
            "temp files left behind: {leftovers:?}"
        );
    }

    // `canonicalize` fails on a path that does not exist yet, so a raw comparison
    // would let `~/.codex/anything/..` through: the check passes, the directory is
    // then created, and the rewrite lands on the user's real config.
    #[test]
    fn the_codex_home_guard_is_not_bypassed_by_dot_dot() {
        let home = dirs::home_dir().expect("home dir");
        let sneaky = home.join(".codex").join("subdir").join("..");
        let err = CodexHome::prepare(Some(sneaky.to_str().unwrap()), false)
            .expect_err("must refuse a path that resolves to ~/.codex");
        assert!(
            format!("{err:#}").contains("refusing to use"),
            "got: {err:#}"
        );
    }

    // The rewrite is destructive, so "could not save a copy" must stop it rather
    // than proceed with a warning.
    #[test]
    fn a_failed_backup_aborts_the_rewrite() {
        let dir = TempDir::new().unwrap();
        let home = home_with(dir.path());
        let original = "# hand-written\nmodel = \"mine\"\n";
        fs::write(dir.path().join("config.toml"), original).unwrap();
        // A directory where the backup file needs to go: fs::copy cannot write it.
        fs::create_dir(dir.path().join("config.toml.bak")).unwrap();

        let err = home
            .write_config(|_| format!("{GENERATED_MARKER}\nmodel = \"generated\"\n"))
            .expect_err("must refuse to overwrite without a backup");
        assert!(format!("{err:#}").contains("back up"), "got: {err:#}");
        // The user's file is still theirs.
        assert_eq!(
            fs::read_to_string(dir.path().join("config.toml")).unwrap(),
            original
        );
    }

    // `config.toml` carries the run's model and x-sc-* attribution headers, and
    // codex reads it at startup, so two runs must not share one durable directory.
    #[test]
    fn a_second_run_does_not_share_a_durable_state_dir() {
        let dir = TempDir::new().unwrap();
        let path = dir.path().join("state");
        let first = CodexHome::prepare(Some(path.to_str().unwrap()), false).expect("first");
        assert!(first.is_durable());
        assert!(
            path.join("run.lock").is_file(),
            "the first run must hold a lock"
        );

        let second = CodexHome::prepare(Some(path.to_str().unwrap()), false).expect("second");
        assert!(
            !second.is_durable(),
            "the second run must fall back to a temp CODEX_HOME instead of sharing config.toml"
        );
        assert_ne!(second.path(), first.path());

        // Ownership is the `flock`, not the file: the lock file stays put and the
        // claim ends when the holder drops. There is therefore no staleness to age
        // out and no window in which two runs both decide a lock is abandoned.
        drop(first);
        let third = CodexHome::prepare(Some(path.to_str().unwrap()), false).expect("third");
        assert!(
            third.is_durable(),
            "the directory must be reusable once the previous run releases it"
        );
        assert_eq!(third.path(), path.as_path());
    }

    #[cfg(unix)]
    #[test]
    fn a_pre_existing_state_dir_is_restricted_to_its_owner() {
        use std::os::unix::fs::PermissionsExt;
        let dir = TempDir::new().unwrap();
        let path = dir.path().join("loose");
        fs::create_dir(&path).unwrap();
        fs::set_permissions(&path, fs::Permissions::from_mode(0o755)).unwrap();

        let home = CodexHome::prepare(Some(path.to_str().unwrap()), false).expect("prepare");
        assert!(home.is_durable());
        let mode = fs::metadata(&path).unwrap().permissions().mode() & 0o777;
        assert_eq!(mode, 0o700, "transcripts must not be world-readable");
    }

    // The merge is the caller's easiest thing to forget, so `write_config` owns it:
    // the renderer is handed the preserved keys instead of a finished string.
    #[test]
    fn write_config_hands_the_renderer_the_preserved_keys() {
        let dir = TempDir::new().unwrap();
        let home = home_with(dir.path());
        home.write_config(|_| {
            "model = \"m\"\n\n[projects.\"/repo\"]\ntrust_level = \"trusted\"\n".to_string()
        })
        .unwrap();

        let mut seen = String::new();
        home.write_config(|preserved| {
            seen = preserved.tables.clone();
            format!("{GENERATED_MARKER}\nmodel = \"m2\"\n{}", preserved.tables)
        })
        .unwrap();
        assert!(
            seen.contains("[projects.\"/repo\"]"),
            "renderer saw: {seen}"
        );
        let after = fs::read_to_string(dir.path().join("config.toml")).unwrap();
        let parsed: toml::Table = toml::from_str(&after).unwrap();
        assert_eq!(
            parsed["projects"]["/repo"]["trust_level"].as_str(),
            Some("trusted")
        );
    }

    #[test]
    fn write_config_rejects_invalid_toml_and_leaves_no_partial_file() {
        let dir = TempDir::new().unwrap();
        let home = home_with(dir.path());
        assert!(home.write_config(|_| "not = = toml".to_string()).is_err());
        assert!(!dir.path().join("config.toml").exists());
        assert!(!dir.path().join("config.toml.tmp").exists());
    }
}
