//! `stratoclave codex -- [args]` subcommand.
//!
//! Launches OpenAI codex as a child process with `CODEX_HOME` pointing
//! at a fresh temp dir we own. That dir contains exactly one file —
//! `config.toml` — describing a `stratoclave` model provider that
//! targets the deployment's `/openai/v1/responses` endpoint. The user's
//! persistent `~/.codex/config.toml` is therefore **never** loaded for
//! this invocation.
//!
//! Why a temp `CODEX_HOME` rather than `-c key=value` overrides? codex
//! resolves model providers as nested TOML; expressing
//! `[model_providers.stratoclave]` via `-c` would require five separate
//! `-c model_providers.stratoclave.<key>=<value>` flags, every one
//! shell-quoted, every one a foot-gun. A single config file is the
//! simpler contract.
//!
//! Lifecycle:
//!
//!   1. Mints an ephemeral, `responses:send`-only `sk-stratoclave-*`
//!      key via `mvp::ephemeral_key::mint_ephemeral_key_scoped`.
//!   2. Creates a temp dir (auto-cleaned on Drop) and writes
//!      `config.toml` pointing codex at the stratoclave base URL and
//!      `env_key = "STRATOCLAVE_OPENAI_KEY"` for the bearer.
//!   3. Spawns codex with `CODEX_HOME=<tempdir>` and the env-key set;
//!      revokes the wrapper key on exit via `ChildLauncher`.
//!
//! Note we deliberately do NOT pass `--ignore-user-config` — that flag
//! tells codex to skip `$CODEX_HOME/config.toml`, which is exactly the
//! file we just wrote. Pointing `CODEX_HOME` at a fresh temp dir is
//! sufficient: the user's `~/.codex/config.toml` is never visible
//! because `~/.codex` is no longer the resolved home.

use anyhow::{Context, Result};
use std::fs;
use std::process::ExitCode;

use tempfile::TempDir;

use super::child_launcher::ChildLauncher;
use super::config::MvpConfig;
use super::ephemeral_key::mint_ephemeral_key_scoped;
use super::tokens::load as load_tokens;

pub async fn run(args: &[String], model_override: Option<&str>) -> Result<ExitCode> {
    let config = MvpConfig::load()?;
    let tokens = load_tokens()?;

    let model = model_override
        .map(String::from)
        .unwrap_or_else(|| config.default_codex_model.clone());

    let base_url = format!(
        "{}{}",
        config.api_endpoint.trim_end_matches('/'),
        config
            .codex_openai_base_path
            .as_deref()
            .unwrap_or("/openai/v1"),
    );

    // Mint the scoped wrapper key first; on failure we never spawn the
    // child and never need to revoke.
    let key = mint_ephemeral_key_scoped(
        &config.api_endpoint,
        &tokens.access_token,
        "stratoclave-codex-wrapper",
        &["responses:send"],
    )
    .await
    .context("Failed to mint ephemeral wrapper key for codex")?;

    let codex_home = build_temp_codex_home(&base_url, &model)
        .context("Failed to write temporary codex config")?;

    eprintln!(
        "[INFO] Launching codex via Stratoclave proxy (base_url={}, model={}, key={})",
        base_url, model, key.key_id
    );
    eprintln!(
        "[INFO] Child process uses an ephemeral responses-only API key; \
         the Cognito bearer is not exported and the user's ~/.codex/config.toml \
         is untouched."
    );

    let result = ChildLauncher::new("codex")
        .env("CODEX_HOME", codex_home.path())
        .env("STRATOCLAVE_OPENAI_KEY", &key.plaintext_key)
        .scrub_stratoclave_tokens()
        .scrub_aws_identity()
        .run_with_revoke(
            args,
            &config.api_endpoint,
            &tokens.access_token,
            &key.key_id,
        )
        .await;

    // Drop the temp dir deterministically so it does not survive the
    // wrapper exit. `TempDir` auto-deletes on Drop, but the explicit
    // drop keeps the failure surface visible if the FS rejects it.
    drop(codex_home);
    result
}

fn build_temp_codex_home(base_url: &str, model: &str) -> Result<TempDir> {
    let dir = TempDir::new().context("TempDir::new for CODEX_HOME")?;
    let body = format!(
        r#"# Auto-generated by `stratoclave codex` — do not edit.
# Lives in a temp `CODEX_HOME` that is deleted when the wrapper exits.

model_provider = "stratoclave"
model = "{model}"

# Bedrock's OpenAI Responses endpoint does not implement the
# `web_search` tool type today. Disabling it here keeps codex from
# sending that tool in its request payload — without this, every
# `/v1/responses` call returns a 400 "Tool type 'web_search' is not
# supported".
web_search = "disabled"

[model_providers.stratoclave]
name                   = "Stratoclave (OpenAI via Bedrock)"
base_url               = "{base_url}"
wire_api               = "responses"
env_key                = "STRATOCLAVE_OPENAI_KEY"
request_max_retries    = 3
stream_max_retries     = 5
stream_idle_timeout_ms = 600000
"#,
    );
    let cfg_path = dir.path().join("config.toml");
    fs::write(&cfg_path, body).with_context(|| {
        format!("write temp codex config to {}", cfg_path.display())
    })?;
    Ok(dir)
}
