//! Enterprise Policy Module
//!
//! Build-time embedded policy settings (includes `OUT_DIR/policy.rs` generated by build.rs).
//! As of Phase 2 (v2.1), only a subset of fields are referenced, so dead_code warnings
//! are suppressed for the entire module.
#![allow(dead_code)]

include!(concat!(env!("OUT_DIR"), "/policy.rs"));
